name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: |
        yarn install
        yarn build
        git config user.name "Actions Bot"
        git add docs
        git commit -m 'auto deploy GitHub Pages'
